### ISSUE TITLE
Error: spawn Xvfb ENOENT, tests fail

### ISSUE THREAD

**Issue by Powersource** [devongovett/blob-stream#4]
I cloned, installed browserify and testling (might want that added to devdependencies?) and got this when running tests:

```
% npm test                                  

> blob-stream@0.1.3 test /mnt/hdd/home/me/prj/web/blob-stream
> browserify test/index.js | testling

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn Xvfb ENOENT
    at _errnoException (util.js:1041:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! Test failed.  See above for more details.
```

Node 8.4.0, npm 5.3.0.

**Comment by Powersource** [comment]
Ignore me, just had to install xvfb https://github.com/substack/testling/issues/66
